/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ButceRouteImport } from './routes/butce'
import { Route as CacRouteImport } from './routes/cac'
import { Route as EdinimRouteImport } from './routes/edinim'
import { Route as FinansmanRouteImport } from './routes/finansman'
import { Route as FizibiliteRouteImport } from './routes/fizibilite'
import { Route as KarlilikRouteImport } from './routes/karlilik'
import { Route as LtvRouteImport } from './routes/ltv'
import { Route as NakitRouteImport } from './routes/nakit'
import { Route as SatisRouteImport } from './routes/satis'
import { Route as TahminRouteImport } from './routes/tahmin'
import { Route as VeriGirisiRouteImport } from './routes/veri-girisi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ButceRoute = ButceRouteImport.update({
  id: '/butce',
  path: '/butce',
  getParentRoute: () => rootRouteImport,
} as any)
const CacRoute = CacRouteImport.update({
  id: '/cac',
  path: '/cac',
  getParentRoute: () => rootRouteImport,
} as any)
const EdinimRoute = EdinimRouteImport.update({
  id: '/edinim',
  path: '/edinim',
  getParentRoute: () => rootRouteImport,
} as any)
const FinansmanRoute = FinansmanRouteImport.update({
  id: '/finansman',
  path: '/finansman',
  getParentRoute: () => rootRouteImport,
} as any)
const FizibiliteRoute = FizibiliteRouteImport.update({
  id: '/fizibilite',
  path: '/fizibilite',
  getParentRoute: () => rootRouteImport,
} as any)
const KarlilikRoute = KarlilikRouteImport.update({
  id: '/karlilik',
  path: '/karlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const LtvRoute = LtvRouteImport.update({
  id: '/ltv',
  path: '/ltv',
  getParentRoute: () => rootRouteImport,
} as any)
const NakitRoute = NakitRouteImport.update({
  id: '/nakit',
  path: '/nakit',
  getParentRoute: () => rootRouteImport,
} as any)
const SatisRoute = SatisRouteImport.update({
  id: '/satis',
  path: '/satis',
  getParentRoute: () => rootRouteImport,
} as any)
const TahminRoute = TahminRouteImport.update({
  id: '/tahmin',
  path: '/tahmin',
  getParentRoute: () => rootRouteImport,
} as any)
const VeriGirisiRoute = VeriGirisiRouteImport.update({
  id: '/veri-girisi',
  path: '/veri-girisi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/butce': typeof ButceRoute
  '/cac': typeof CacRoute
  '/edinim': typeof EdinimRoute
  '/finansman': typeof FinansmanRoute
  '/fizibilite': typeof FizibiliteRoute
  '/karlilik': typeof KarlilikRoute
  '/ltv': typeof LtvRoute
  '/nakit': typeof NakitRoute
  '/satis': typeof SatisRoute
  '/tahmin': typeof TahminRoute
  '/veri-girisi': typeof VeriGirisiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/butce': typeof ButceRoute
  '/cac': typeof CacRoute
  '/edinim': typeof EdinimRoute
  '/finansman': typeof FinansmanRoute
  '/fizibilite': typeof FizibiliteRoute
  '/karlilik': typeof KarlilikRoute
  '/ltv': typeof LtvRoute
  '/nakit': typeof NakitRoute
  '/satis': typeof SatisRoute
  '/tahmin': typeof TahminRoute
  '/veri-girisi': typeof VeriGirisiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/butce': typeof ButceRoute
  '/cac': typeof CacRoute
  '/edinim': typeof EdinimRoute
  '/finansman': typeof FinansmanRoute
  '/fizibilite': typeof FizibiliteRoute
  '/karlilik': typeof KarlilikRoute
  '/ltv': typeof LtvRoute
  '/nakit': typeof NakitRoute
  '/satis': typeof SatisRoute
  '/tahmin': typeof TahminRoute
  '/veri-girisi': typeof VeriGirisiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/butce'
    | '/cac'
    | '/edinim'
    | '/finansman'
    | '/fizibilite'
    | '/karlilik'
    | '/ltv'
    | '/nakit'
    | '/satis'
    | '/tahmin'
    | '/veri-girisi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/butce'
    | '/cac'
    | '/edinim'
    | '/finansman'
    | '/fizibilite'
    | '/karlilik'
    | '/ltv'
    | '/nakit'
    | '/satis'
    | '/tahmin'
    | '/veri-girisi'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/butce'
    | '/cac'
    | '/edinim'
    | '/finansman'
    | '/fizibilite'
    | '/karlilik'
    | '/ltv'
    | '/nakit'
    | '/satis'
    | '/tahmin'
    | '/veri-girisi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ButceRoute: typeof ButceRoute
  CacRoute: typeof CacRoute
  EdinimRoute: typeof EdinimRoute
  FinansmanRoute: typeof FinansmanRoute
  FizibiliteRoute: typeof FizibiliteRoute
  KarlilikRoute: typeof KarlilikRoute
  LtvRoute: typeof LtvRoute
  NakitRoute: typeof NakitRoute
  SatisRoute: typeof SatisRoute
  TahminRoute: typeof TahminRoute
  VeriGirisiRoute: typeof VeriGirisiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/butce': {
      id: '/butce'
      path: '/butce'
      fullPath: '/butce'
      preLoaderRoute: typeof ButceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cac': {
      id: '/cac'
      path: '/cac'
      fullPath: '/cac'
      preLoaderRoute: typeof CacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edinim': {
      id: '/edinim'
      path: '/edinim'
      fullPath: '/edinim'
      preLoaderRoute: typeof EdinimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finansman': {
      id: '/finansman'
      path: '/finansman'
      fullPath: '/finansman'
      preLoaderRoute: typeof FinansmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fizibilite': {
      id: '/fizibilite'
      path: '/fizibilite'
      fullPath: '/fizibilite'
      preLoaderRoute: typeof FizibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karlilik': {
      id: '/karlilik'
      path: '/karlilik'
      fullPath: '/karlilik'
      preLoaderRoute: typeof KarlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ltv': {
      id: '/ltv'
      path: '/ltv'
      fullPath: '/ltv'
      preLoaderRoute: typeof LtvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nakit': {
      id: '/nakit'
      path: '/nakit'
      fullPath: '/nakit'
      preLoaderRoute: typeof NakitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satis': {
      id: '/satis'
      path: '/satis'
      fullPath: '/satis'
      preLoaderRoute: typeof SatisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tahmin': {
      id: '/tahmin'
      path: '/tahmin'
      fullPath: '/tahmin'
      preLoaderRoute: typeof TahminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veri-girisi': {
      id: '/veri-girisi'
      path: '/veri-girisi'
      fullPath: '/veri-girisi'
      preLoaderRoute: typeof VeriGirisiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ButceRoute: ButceRoute,
  CacRoute: CacRoute,
  EdinimRoute: EdinimRoute,
  FinansmanRoute: FinansmanRoute,
  FizibiliteRoute: FizibiliteRoute,
  KarlilikRoute: KarlilikRoute,
  LtvRoute: LtvRoute,
  NakitRoute: NakitRoute,
  SatisRoute: SatisRoute,
  TahminRoute: TahminRoute,
  VeriGirisiRoute: VeriGirisiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
