/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ButceRouteImport } from './routes/butce'
import { Route as SatisRouteImport } from './routes/satis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButceRoute = ButceRouteImport.update({
  id: '/butce',
  path: '/butce',
  getParentRoute: () => rootRouteImport,
} as any)
const SatisRoute = SatisRouteImport.update({
  id: '/satis',
  path: '/satis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/butce': typeof ButceRoute
  '/satis': typeof SatisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/butce': typeof ButceRoute
  '/satis': typeof SatisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/butce': typeof ButceRoute
  '/satis': typeof SatisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/butce' | '/satis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/butce' | '/satis'
  id: '__root__' | '/' | '/butce' | '/satis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButceRoute: typeof ButceRoute
  SatisRoute: typeof SatisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/butce': {
      id: '/butce'
      path: '/butce'
      fullPath: '/butce'
      preLoaderRoute: typeof ButceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satis': {
      id: '/satis'
      path: '/satis'
      fullPath: '/satis'
      preLoaderRoute: typeof SatisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButceRoute: ButceRoute,
  SatisRoute: SatisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
